routes/web.php
<?php

use App\Http\Controllers\CategorieController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProduitController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
..
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class,"index"])->name("index");

Route::post('/add-panier' ,[HomeController::class,"addPanier"])->name("add-panier");
Route::get('/show-panier' ,[HomeController::class,"showPanier"])->name("show-panier");
Route::get('/clear-panier' ,[HomeController::class,"clearPanier"])->name("clear-panier-item");
Route::post('/remove-panier-item' ,[HomeController::class,"removePanier"])->name("remove-panier-item");

Route::get("/categories/search", [CategorieController::class,"search"])->name("categories.search");
Route::get("/produits/search", [ProduitController::class,"search"])->name("produits.search");
Route::resource("categories",CategorieController::class);
Route::resource("produits",ProduitController::class);
// Route::get('/produits', [ProduitController::class, 'filter'])->name('produits.filter');
// Route::get('/produits/filter', [ProduitController::class, 'index'])->name('produits.index');

resources/views/categories/create.blade.php
 @extends('layouts.admin')
 @section('title', 'Ajouter une categorie')
 @section('content')
     <h1>Creer une nouvelle categorie</h1>
     <form action="{{ route('categories.store') }}" method="POST">
         @csrf
         <div class="input-group-text">
             <label for="designation">Designation:</label>
             <input name="designation" class="form-control mt-0 ms-2" type="text" value="" aria-label="Checkbox for following text input">
         </div>
         <div class="input-group-text mt-2">
             <label for="description">Description:</label>
             <input name="description" class="form-control mt-0 ms-2" type="text" value="" aria-label="Checkbox for following text input">
         </div>
         <div class="mt-3">
             <input class="btn btn-primary" type="submit" value="Ajouter">
         </div>
     </form>
     <div>
         @if ($errors->any())
             <ul>
                 @foreach ($errors->all() as $er)
                     <li>{{ $er }}</li>
                 @endforeach
             </ul>
         @endif
     </div>
 @endsection

resources/views/categories/edit.blade.php
@extends('layouts.admin')
@section('title','Modifier une categorie')
@section('content')
    <h1>Modifier la categorie num {{$cat->id}}</h1>
    <form action="{{route('categories.update',["category"=>$cat->id])}}" method="POST">
        @csrf
        @method('PUT')
        <div>
        <label for="designation">Designation</label>
        <input type="text" name="designation" id="designation" value="{{old('designation',$cat->designation)}}">
        </div>
        <div>
        <label for="description">Description</label>
        <textarea name="description" id="description" cols="30" rows="10" >{{old('designation',$cat->description)}}</textarea>

        </div>
        <div>
            <input type="submit" value="Modifier">
        </div>
    </form>
    <div>
        @if($errors->any())
        <ul>
            @foreach($errors->all() as $er)
                <li>{{$er}}</li>
            @endforeach
        </ul>
        @endif
    </div>

@endsection

resources/views/categories/index.blade.php
@extends('layouts.admin')
@section('title', 'Gestion des categories')
@section('content')

    {{-- Search and Ajouter --}}
    <h1 class="mt-5 mb-3">Liste des categories</h1>
    <form action="{{ route('categories.search') }}" method="get">
        <div class="input-group mb-3">
            <input type="text" class="form-control" name="designation">
            <button class="input-group-text" type="submit">
                <img src="{{ asset('/search.png') }}">
            </button>
            <div id="ajouter"><a class="ms-2 btn btn-primary" href="{{ route('categories.create') }}">Ajouter
                    categorie</a></div>
        </div>
    </form>

    {{-- reset --}}
    <a href="{{ route('categories.index') }}">list des categories</a>

    {{-- Viewer --}}
    <table class="table table-striped">
        <thead>
            <th>Id</th>
            <th>Designation</th>
            <th>Description</th>
            <th colspan="3">Actions</th>
        </thead>
        <tbody>
            @foreach ($categories as $cat)
                <tr>
                    <td>{{ $cat->id }}</td>
                    <td>{{ $cat->designation }}</td>
                    <td>{{ $cat->description }}</td>
                    <td>
                        <a href="{{ route('categories.show', ['category' => $cat->id]) }}">
                            <img src="{{ asset('/details.png') }}">
                        </a>
                    </td>
                    <td>
                        <a class="btn btn-success" href="{{ route('categories.edit', ['category' => $cat->id]) }}">
                            <img src="{{ asset('/change.png') }}">
                        </a>
                    </td>
                    <td>
                        <form action="{{ route('categories.destroy', ['category' => $cat->id]) }}" method="POST">
                            @method('DELETE')
                            @csrf
                            <button class="btn btn-danger" type="submit"
                                onclick="return confirm('voulez-vous supprimer cette categorie?')">
                                <img src="{{ asset('/delete.png') }}">
                            </button>

                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/categories/show.blade.php
 @extends('layouts.admin')
 @section('title','Detail d \'une categorie')
 @section('content')
    <a href="{{route('categories.index')}}">Retourner vers la liste des categories</a>
    <h1>Detail de la categorie Num {{$cat->id}}</h1>
    <div>
        <p><strong>Designation:</strong> {{$cat->designation}}</p>
        <p><strong>Description:</strong> {{$cat->description}}</p>
    </div>
@endsection