routes/web.php
<?php

use App\Http\Controllers\CategorieController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProduitController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
..
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class,"index"])->name("index");

Route::post('/add-panier' ,[HomeController::class,"addPanier"])->name("add-panier");
Route::get('/show-panier' ,[HomeController::class,"showPanier"])->name("show-panier");
Route::get('/clear-panier' ,[HomeController::class,"clearPanier"])->name("clear-panier-item");
Route::post('/remove-panier-item' ,[HomeController::class,"removePanier"])->name("remove-panier-item");

Route::get("/categories/search", [CategorieController::class,"search"])->name("categories.search");
Route::get("/produits/search", [ProduitController::class,"search"])->name("produits.search");
Route::resource("categories",CategorieController::class);
Route::resource("produits",ProduitController::class);
// Route::get('/produits', [ProduitController::class, 'filter'])->name('produits.filter');
// Route::get('/produits/filter', [ProduitController::class, 'index'])->name('produits.index');

app/Models/Produit.php
<?php

namespace App\Models;

use App\Models\Categorie;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Produit extends Model
{
    use HasFactory;
    protected $fillable =[
        'designation',
        'prix_u',
        'quantite_stock',
        'categorie_id',
        'photo',
    ];
    public function categorie(){
        return  $this->belongsTo(Categorie::class);
    }
    // public function scopeFilterByPrice($query, $minPrice, $maxPrice)
    // {
    //     if ($minPrice) {
    //         $query->where('prix_u', '>=', $minPrice);
    //     }

    //     if ($maxPrice) {
    //         $query->where('prix_u', '<=', $maxPrice);
    //     }

    //     return $query;
    // }
}

app/Http/Controllers/ProduitController.php
<?php

namespace App\Http\Controllers;

use App\Models\Produit;
use App\Models\Categorie;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Rules\File;

class ProduitController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $produits=Produit::paginate(10);
        $query_builder=Produit::query();

        $designiation=$request->input("designation");
        $min_price=$request->input("min_price");
        $max_price=$request->input("max_price");
        
        if($designiation){
            $query_builder->where("designation","like","%".$designiation."%");
            $produits = $query_builder->paginate();

        }

        if( $min_price and $max_price ){
            $query_builder->whereBetween("prix_u" ,[$min_price,$max_price]);
            $produits = $query_builder->paginate();
        }




        

        return view("produits.index",compact('produits'));
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $cats=Categorie::all();
        return view('produits.create',compact('cats'));
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'designation'=>'required|unique:categories,designation',
            'prix_u'=>'required|numeric',
            'quantite_stock'=>'required|numeric',
            'categorie_id'=>'required',
            'photo' => 'image|mimes:jpeg,jpg,png,gif,svg|max:512000'
        
        ]);

        if($request->hasFile('photo')){
            $imagePath=$request->file('photo')->store('products/images','public');
            $validatedData['photo']=$imagePath;
        }
        Produit::create($validatedData);
        return  redirect()->route('produits.index');
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
        $prod=Produit::find($id);
        return view('produits.show')->with("prod",$prod);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $prod=Produit::find($id);
        $cats=Categorie::all();
        $data = ["prod"=>$prod,"cats"=>$cats];

        return view('produits.edit',compact('data'));
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $request->validate([
            'designation'=>'required|unique:categories,designation',
            'prix_u'=>'required|numeric',
            'quantite_stock'=>'required|numeric|decimal',
            'categorie_id'=>'required',
            'photo' => [
                'required',
                File::image()
                    ->min(1024)
                    ->max(12 * 1024)
                    ->dimensions(Rule::dimensions()->maxWidth(1000)->maxHeight(500))
                    
            ],
        

        ]);
        $cat=Produit::find($id);
        $cat->update($request->all());
        return redirect()->route('produits.index');
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Produit::destroy($id);
        return  redirect()->route('produits.index');
    }
    public function search(Request $request){
       
        $param=$request->query('designation');
        $produits=Produit::where('designation','like','%'.$param.'%')->get();
        return view('produits.index',compact('produits'));
    }
    // public function filter(Request $request)
    // {
    //     $minPrice = $request->input('min_price');
    //     $maxPrice = $request->input('max_price');

    //     $produits = Produit::filterByPrice($minPrice, $maxPrice)->paginate(10);

    //     return view('produits.index', compact('produits', 'minPrice', 'maxPrice'));
    // }
}

resources/views/produits/create.blade.php
@extends('layouts.admin')
@section('title', 'Ajouter un produit')
@section('content')
    <h1>Creer une nouvelle produit</h1>
    <form action="{{ route('produits.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="input-group-text">
            <label for="designation">Designation:</label>
            <input name="designation" class="form-control mt-0 ms-2" type="text"
                aria-label="Checkbox for following text input">
        </div>

        <div class="input-group-text mt-2">
            <label for="description">Prix Unite:</label>
            <input name="prix_u" class="form-control mt-0 ms-2" type="text" value=""
                aria-label="Checkbox for following text input">
        </div>

        <div class="input-group-text mt-2">
            <label for="description">Quantite Stock:</label>
            <input name="quantite_stock" class="form-control mt-0 ms-2" type="text" value=""
                aria-label="Checkbox for following text input">
        </div>

        <select class="form-select @error("categorie_id") is-invalid @enderror" name="categorie_id" id="cat_id">
            <option value="" selected>Select categorie</option>
            @foreach ($cats as $item)
                <option value="{{ $item->id }}">{{ $item->designation }}</option>
            @endforeach
        </select>
        <label for="photo">image</label>
        <input type="file" name="photo"  alt="image" >

        <div class="mt-3">
            <input type="submit" value="Ajouter">
        </div>

    </form>
    <div>
        @if ($errors->any())
            <ul>
                @foreach ($errors->all() as $er)
                    <li>{{ $er }}</li>
                @endforeach
            </ul>



        @endif
    </div>
@endsection

resources/views/produits/edit.blade.php
@extends('layouts.admin')
@section('title', 'Ajouter un produit')
@section('content')
    <h1>Creer une nouvelle produit</h1>
    <form action="{{ route('produits.update', ['produit' => $data["prod"]->id]) }}" method="POST">
        @csrf
        @method('PUT')
        <div>
            <label for="designation">Designation</label>
            <input type="text" name="designation" id="designation" value="{{ old('designation', $data["prod"]->designation) }}">
        </div>

        <div>
            <label for="prix_u">prix unite</label>
            <input type='text' name="prix_u" id="prix_u" cols="30" rows="10"
                value="{{ old('prix_u', $data["prod"]->prix_u) }}">
        </div>
        <div>
            <label for="quantite_stock">quantite stock</label>
            <input type='text' name="quantite_stock" id="quantite_stock" cols="30" rows="10"
                value="{{ old('quantite_stock', $data["prod"]->quantite_stock) }}">
        </div>
        <select class="form-select @error("categorie_id") is-invalid @enderror" name="categorie_id" id="cat_id">
            <option value="" selected>Select categorie Id</option>
            @foreach ($data["cats"] as $item)
                <option value="{{ $item->id }}">{{ $item->designation }}</option>
            @endforeach
        </select>
        <div>
            <input type="submit" value="modifier">
        </div>
    </form>
    <div>
        @if ($errors->any())
            <ul>
                @foreach ($errors->all() as $er)
                    <li>{{ $er }}</li>
                @endforeach
            </ul>


        @endif
    </div>
@endsection

resources/views/produits/index.blade.php
@extends('layouts.admin')
@section('title', 'Gestion des produits')
@section('content')



    {{-- Search and Ajouter --}}
    <h1 class="mt-5 mb-3">Liste des Produit</h1>
    <form action="{{ route('produits.index') }}" method="get" >
        <div class="input-group mb-3">
            <label for="designation">designation</label>
            <input type="text" class="form-control" name="designation" value="{{old("designation")}}">
            <label for="min_price">min price</label>
            <input class="form-control" type="text" name="min_price" value="{{old("min_price")}}">
            <label for="min_price">max price</label>
            <input class="form-control" type="text" name="max_price" value="{{old("max_price")}}">
           <input type="submit" value="submit">
    </form>
    {{-- <form action="" method="GET">
        <label for="min_price">Min Price:</label>
        <input type="text" name="min_price" id="min_price" value="{{ old("minPrice") }}">
        {{-- <input type="text" name="min_price" id="min_price"> --}}
{{-- 

        <label for="max_price">Max Price:</label>
        <input type="text" name="max_price" id="max_price" value="{{ old("maxPrice") }}">
        <input type="text" name="max_price" id="max_price">


        <button type="submit">Filter</button>
    </form> -- --}}
    <div id="ajouter">
        <a class="ms-2 btn btn-primary" href="{{ route('produits.create') }}">Ajouter Produit</a>
    </div>
    </div>


    {{-- reset --}}
    <a href="{{ route('produits.index') }}">list des produits</a>

    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Designation</th>
            <th>prix unite</th>
            <th>quantite en stock</th>
            <th>categorie id</th>
            <th colspan="3">Actions</th>
        </tr>
        @foreach ($produits as $prod)
            <tr>
                <td>{{ $prod->id }}</td>
                <td>{{ $prod->designation }}</td>
                <td>{{ $prod->prix_u }}</td>
                <td>{{ $prod->quantite_stock }}</td>
                <td>{{ $prod->categorie_id }}</td>

                <td>
                    <a href="{{ route('produits.show', ['produit' => $prod->id]) }}">
                        <img src="{{ asset('/details.png') }}">
                    </a>
                </td>
                <td>
                    <a class="btn btn-success" href="{{ route('produits.edit', ['produit' => $prod->id]) }}">
                        <img src="{{ asset('/change.png') }}">
                    </a>
                </td>
                <td>
                    <form action="{{ route('produits.destroy', ['produit' => $prod->id]) }}" method="POST">
                        @method('DELETE')
                        @csrf
                        <button class="btn btn-danger" type="submit"
                            onclick="return confirm('voulez-vous supprimer ce produit?')">
                            <img src="{{ asset('/delete.png') }}">
                        </button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
    <div>
        <p> results {{$produits->count()}} of {{$produits->total()}}</p>
        <div>
            
        </div>
    </div>
    {{ $produits->links() }}
@endsection

resources/views/produits/show.blade.php
@extends('layouts.admin')
@section('title','Detail d \'une categorie')
@section('content')
    <a href="{{route('produits.index')}}">Retourner vers la liste des produits</a>
    <h1>Detail de la produit Num {{$prod->id}}</h1>
    <img src="{{asset("storage/$prod->photo")}}" alt="product image">
    <div>
        <p><strong>Designation:</strong> {{$prod->designation}}</p>
        <p><strong>prix unitere:</strong> {{$prod->prix_u}}</p>
        <p><strong>quantite on stock:</strong> {{$prod->quantite_stock}}</p>
        <p><strong>id categorie:</strong> {{$prod->categorie_id}}</p>
    </div>
@endsection